# 1.列表如何转nd array

In [1]:
import numpy as np
list1=[1,2,3,4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [2]:
oneArray=np.array(list1) #列表转一维向量，格式上看，列表带逗号，向量不带逗号
print(oneArray)
print(type(oneArray))

[1 2 3 4]
<class 'numpy.ndarray'>


# 2.创建向量与矩阵

In [3]:
#创建一维数组（向量）
vec1=np.arange(1,11,2) #等价于先生成range(1,11,2)的列表，再转化为张量。 np.arange()返回的是ndarray
print(vec1)
print(type(vec1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [5]:
#二维列表转nd array
list2=[[1,2],[3,4],[5,6]] #每一个元素可以看成一个行向量

twoArray=np.array(list2)
print(twoArray) #一行一个列表，有形状的 。 也不带逗号
print(type(twoArray))
print(list2)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1, 2], [3, 4], [5, 6]]


In [6]:
# 二维数组转换为二维列表
twoArray.tolist() #ndarray转化为列表

[[1, 2], [3, 4], [5, 6]]

# 3.常用属性

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.ndim)    # 2 → 维度（几维数组）
print(arr.shape)   # (2, 3) → 形状（行数, 列数）  （0 axis，1axis）
print(arr.size)    # 6 → 元素总数
print(arr.dtype)   # int32 → 元素的数据类型   数据范围：-21亿~+21亿

# 👉 shape 是 ML 中最重要的属性，所有模型输入都要求固定的 shape（比如图像输入 shape=(224,224,3)）

2
(2, 3)
6
int32


# 4.改变形状

In [9]:
M1=np.array([[1,2,3],[4,5,6]])
print(M1)

#方法一
M1.shape=(3,2) #改变形状后，地址没变
print(M1)

#方法二：
M2=M1.reshape(1,6)
print(M2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
