# 1.列表如何转nd array

In [2]:
import numpy as np
list1=[1,2,3,4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [3]:
oneArray=np.array(list1) #列表转一维向量，格式上看，列表带逗号，向量不带逗号
print(oneArray)
print(type(oneArray))

[1 2 3 4]
<class 'numpy.ndarray'>


# 2.创建向量与矩阵

In [4]:
#创建一维数组（向量）
vec1=np.arange(1,11,2) #等价于先生成range(1,11,2)的列表，再转化为张量。 np.arange()返回的是ndarray
print(vec1)
print(type(vec1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [5]:
#二维列表转nd array
list2=[[1,2],[3,4],[5,6]] #每一个元素可以看成一个行向量

twoArray=np.array(list2)
print(twoArray) #一行一个列表，有形状的 。 也不带逗号
print(type(twoArray))
print(list2)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1, 2], [3, 4], [5, 6]]


In [6]:
# 二维数组转换为二维列表
twoArray.tolist() #ndarray转化为列表

[[1, 2], [3, 4], [5, 6]]

# 3.常用属性

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.ndim)    # 2 → 维度（几维数组）
print(arr.shape)   # (2, 3) → 形状（行数, 列数）  （0 axis，1axis）
print(arr.size)    # 6 → 元素总数
print(arr.dtype)   # int32 → 元素的数据类型   数据范围：-21亿~+21亿

# 👉 shape 是 ML 中最重要的属性，所有模型输入都要求固定的 shape（比如图像输入 shape=(224,224,3)） 

2
(2, 3)
6
int32


# 4.改变形状

In [8]:
M1=np.array([[1,2,3],[4,5,6]])
print(M1)

#方法一
M1.shape=(3,2) #改变形状后，地址没变
print(M1)

#方法二：
M2=M1.reshape(1,6)
print(M2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [9]:
# 转成三维
# 看括号，最外层是0轴，依次是1轴，2轴。 前面的要有整体思维，看后面的要看局部
vec2=np.arange(0,24,1)
T1=vec2.reshape(2,3,4) #看一个nd array，先看其形状，再依次看轴的元素。
print(T1)
print(T1.shape)
print(T1.ndim)

#以三维为例，轴0个数：矩阵个数，把矩阵当成一个整体    轴1：向量个数，以向量为单位   轴2：向量的每个分量    由此可以快速得出张量的尺寸shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


# 5.NumPy的数据类型

In [12]:
import random
f=np.array([1,2,3,4,5],dtype=np.int16) #给每个元素设置数据类型，可节省空间
print(f)
print(f.itemsize) #2B=16b

[1 2 3 4 5]
2


# 6.数组的计算

In [13]:
#1.算数运算，向量化
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)  # [ 6  8 10 12]
print(a - b)  # [-4 -4 -4 -4]
print(a * b)  # [ 5 12 21 32]
print(a / b)  # [0.2        0.33333333 0.42857143 0.5       ]
print(a ** 2) # [ 1  4  9 16]

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [14]:
# 2.广播机制：当两个数组形状不同时，NumPy 会自动扩展较小的数组（扩展copy一份自己），让它们形状匹配，从而进行运算。
#（一）向量+标量
a = np.array([[1,2,3], [4,5,6]])
print(a + 10)  # 每个元素都加10
# [[11 12 13]
#  [14 15 16]]

#（二）二维数组+一维数组（矩阵+向量)    
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10,20,30])  # shape=(3,) ，只有一行。       a,b的维度不匹配时，但有一个的维度（二者不相等的维）是1，即可广播。  例如：(10,128,128)第一个维度代表样本数，可以对单样本操作，再广播。

print(a + b)
# [[11 22 33]
#  [14 25 36]]

[[11 12 13]
 [14 15 16]]
[[11 22 33]
 [14 25 36]]


In [15]:
# 3.矩阵运算
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

# 矩阵乘法（两种写法等价）
print(np.dot(a, b))
print(a @ b)
# [[19 22]
#  [43 50]]

# 矩阵转置
print(a.T)
# [[1 3]
#  [2 4]]

# 矩阵求逆
print(np.linalg.inv(a))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# 7.轴练习
轴 = 数组的维度方向，指定哪个轴，就沿着哪个方向进行操作。<br>
记住口诀：沿哪个轴求和，哪个轴就消失（压缩哪个轴）<br>
二维 shape=(行，列)：axis=0 竖着算（按列聚合），axis=1 横着算（按行聚合）<br>
一定要明确计算后的形状（尺寸）。

In [2]:
import numpy as np
arr = np.array([
    [1,5,3],
    [4,2,6]
])

print(np.sum(arr, axis=0)) #哪个轴求和，哪个轴就没了（压缩）。最终结果与轴1形状一致。 也可以画箭头⬆️，看方向，根据方向进行运算。以行为单位运算。
print(np.max(arr, axis=0))
print(np.sum(arr, axis=1)) #最终结果与轴0形状一致。 “按行求和”。 沿轴1方向把面包一巴掌拍扁。✅️
print(np.sum(arr))

[5 7 9]
[4 5 6]
[ 9 12]
21


In [6]:
#要明确求和后的形状，沿哪个轴求和，哪个轴消失
a=np.arange(24).reshape(2,3,4)
print(np.sum(a,axis=0).shape) #按轴0求和，轴0消失
print(np.sum(a,axis=1).shape)
print(np.sum(a,axis=2).shape)
print(a.shape)

(3, 4)
(2, 4)
(2, 3)
(2, 3, 4)


一、核心映射：轴 = 数据的分类维度<br>
在 99% 的数据分析和机器学习场景中，二维数组的形状永远是：shape = (样本数, 特征数)<br>


axis=0 = 样本维度：沿着这个轴走，你在遍历不同的样本<br>
axis=1 = 特征维度：沿着这个轴走，你在遍历同一个样本的不同属性<br>

这就是轴最根本的现实意义。所有的聚合操作（求和、求平均、求最大），本质上都是在某一个分类维度上进行汇总。<br>

六、一句话终极总结
轴就是你观察数据的角度：<br>
axis=0：站在 "上帝视角"，看所有样本的同一个特征<br>
axis=1：站在 "个体视角"，看同一个样本的所有特征<br>
所有的轴操作，本质上都是切换你的观察角度，对同一类事物进行批量统计分析。这就是 NumPy 轴设计的根本目的，也是它在数据科学中如此强大的原因。<br>

# 8.索引与切片

In [7]:
#1.一维数组的索引与切片
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

print(a[0])    # 0 → 单个元素
print(a[2:5])  # [2 3 4] → 切片，左闭右开
print(a[:5])   # [0 1 2 3 4] → 前5个元素
print(a[5:])   # [5 6 7 8 9] → 从第5个到最后
print(a[::2])  # [0 2 4 6 8] → 步长2

0
[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [8]:
#2.二维数组的索引与切片
# 以逗号为分界，逗号前描述行，逗号后描述列。均可用切片语句描述：序列[start:stop:step]

b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 单个元素：第0行第1列
print(b[0,1])  # 2

# 第0行所有列
print(b[0,:])  # [1 2 3 4]

# 所有行第1列
print(b[:,1])  # [ 2  6 10]

# 前2行，前2列
print(b[:2, :2])
# [[1 2]
#  [5 6]]

2
[1 2 3 4]
[ 2  6 10]
[[1 2]
 [5 6]]


# 9.数组的添加、删除、去重

In [16]:
#1.添加——append
a1=np.array([[1,2,3],[4,5,6]])
print('初始数组：')
print(a1)

print('向数组添加元素：')
print(np.append(a1,[7,8,9]))

print('沿轴 0 添加元素：')
print(np.append(a1, [[7, 8, 9]], axis=0))

print('沿轴 1 添加元素：')
print(np.append(a1, [[5, 5, 5], [7, 8, 9]], axis=1))
#注：np.append()根本不会修改原数组a1，它每次都是创建一个全新的数组返回。
#列表的append会原地修改，但是np.append不会修改原数组。

初始数组：
[[1 2 3]
 [4 5 6]]
向数组添加元素：
[1 2 3 4 5 6 7 8 9]
沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [22]:
#添加——insert
a2 = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a2)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a2, 3, [11, 12]))  #未指定轴时，先展开，按展开后的位置插入。
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a2, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a2, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [23]:
#删除——delete
a3 = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a3)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。') #未指明轴时，此时先展开，后删除
print(np.delete(a3,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a3,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




# 10.numpy的数学计算

In [25]:
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)
# 5. 数据的比较
result = np.maximum( [-2,-1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2,-1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2,-1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；
# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr= np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''
# 8. argmin 求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result,res)
# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)
# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)
# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median
'''通用函数：
numpy.sqrt(array) 平方根函数
numpy.exp(array) e^array[i]的数组
numpy.abs/fabs(array) 计算绝对值
numpy.square(array)计算各元素的平方 等于array 2
numpy.log/log10/log2(array)计算各元素的各种对数
numpy.sign(array) 计算各元素正负号
numpy.isnan(array) 计算各元素是否为NaN
numpy.isinf(array) 计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回
numpy.ceil(array) 向上取整,也就是取比这个数大的整数
numpy.floor(array) 向下取整,也就是取比这个数小的整数
numpy.rint(array) 四舍五入
numpy.trunc(array) 向 0 取整
numpy.cos(array) 正弦值
numpy.sin(array) 余弦值
numpy.tan(array) 正切值
numpy.add(array1,array2) 元素级加法
numpy.subtract(array1,array2) 元素级减法
numpy.multiply(array1,array2) 元素级乘法
numpy.divide(array1,array2)元素级除法 array1./array2
numpy.power(array1,array2) 元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN
numpy.mod(array1,array2) 元素级求模
numpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

88
[82 88]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[2 1] [75 81]
[2.94392029 3.29983165]
13


'通用函数：\nnumpy.sqrt(array) 平方根函数\nnumpy.exp(array) e^array[i]的数组\nnumpy.abs/fabs(array) 计算绝对值\nnumpy.square(array)\n计算各元素的平方 等于array 2\nnumpy.log/log10/log2(array)\n计算各元素的各种对数\nnumpy.sign(array) 计算各元素正负号\nnumpy.isnan(array) 计算各元素是否为NaN\nnumpy.isinf(array) 计算各元素是否为NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array) 向上取整,也就是取比这个数大的整数\nnumpy.floor(array) 向下取整,也就是取比这个数小的整数\nnumpy.rint(array) 四舍五入\nnumpy.trunc(array) 向 0 取整\nnumpy.cos(array) 正弦值\nnumpy.sin(array) 余弦值\nnumpy.tan(array) 正切值\nnumpy.add(array1,array2) 元素级加法\nnumpy.subtract(array1,array2) 元素级减法\nnumpy.multiply(array1,array2) 元素级乘法\nnumpy.divide(array1,array2)\n元素级除法 array1./array2\nnumpy.power(array1,array2) 元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN\nnumpy.mod(array1,array2) 元素级求模\nnumpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/equal/not_equal (array1

# 11.数组的拼接与分割

In [26]:
# 两个形状完全相同的二维数组：2行2列
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

1. np.concatenate：在现有轴上拼接（不增加维度）
* 这是最基础、最常用的拼接函数，不会改变数组的总维度，只是在已有的某个轴上延长长度。

In [28]:
# 沿轴0（行方向/垂直方向）拼接
print('沿轴0连接两个数组：')
print(np.concatenate((a, b), axis=0))

沿轴0连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2. np.stack：创建新轴来拼接（会增加维度）⭐ 最容易混淆
* 和concatenate的本质区别：stack会凭空增加一个新的维度，把原来的数组作为新维度下的元素。
3. 核心规则
* 要求：所有输入数组的形状必须完全相同
* 本质：把多个独立的数组，打包成一个更高维度的数组
* 最常用场景：深度学习中，把多张(28,28)的图片，打包成一个(批次大小,28,28)的训练批次

In [29]:
# 沿新轴0拼接
print('沿轴0堆叠两个数组：')
print(np.stack((a, b), axis=0))

# 沿新轴1拼接
print('\n沿轴1堆叠两个数组：')
print(np.stack((a, b), axis=1))

沿轴0堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

沿轴1堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


堆叠轴	结果形状	维度顺序	核心含义	实际使用频率
axis=0	(2, 3, 4)	班级 → 学生 → 科目	按 "班级" 打包	90%
axis=1	(3, 2, 4)	学生 → 班级 → 科目	按 "学生" 打包	<1%
axis=-1	(3, 4, 2)	学生 → 科目 → 班级	按 "科目" 打包	9%

In [30]:
#关于stack的理解：有点像磁盘的逻辑结构（盘面号，柱面号，扇区号）

# 一班成绩：3个学生，4门课（语文、数学、英语、物理）
class1 = np.array([
    [90, 85, 92, 88],  # 学生1
    [78, 95, 80, 91],  # 学生2
    [85, 82, 88, 90]   # 学生3
])

# 二班成绩：同样3个学生，4门课
class2 = np.array([
    [88, 90, 85, 92],  # 学生1
    [92, 87, 90, 85],  # 学生2
    [80, 93, 87, 89]   # 学生3
])

# 维度含义：(班级数, 学生数, 科目数)
# 直观理解：像一本两页的成绩册
# 第 0 页（第一个大括号）：一班所有学生的成绩
# 第 1 页（第二个大括号）：二班所有学生的成绩
# 每页里的每一行：对应一个学生的 4 门课成绩
print('1. 沿 axis=0 堆叠（最常用）')
stack0 = np.stack((class1, class2), axis=0)
print("形状：", stack0.shape)  # (2, 3, 4)
print("\n结果：")
print(stack0)


# 维度含义：(学生数, 班级数, 科目数)
# 直观理解：按 "学生" 分组，每个学生下面放他在两个班的成绩
# 第 0 行（第一个大括号）：学生 1 的成绩
# 第 0 列：学生 1 在一班的成绩
# 第 1 列：学生 1 在二班的成绩
# 第 1 行：学生 2 的成绩
# 第 2 行：学生 3 的成绩
print('2. 沿 axis=1 堆叠（极少用')
stack1 = np.stack((class1, class2), axis=1)
print("形状：", stack1.shape)  # (3, 2, 4)
print("\n结果：")
print(stack1)


# 维度含义：(学生数, 科目数, 班级数)
# 直观理解：每个格子里存的是 "同一个学生同一门课，在两个班的成绩"
# 第 0 行第 0 列 [90, 88]：学生 1 的语文成绩，一班 90，二班 88
# 第 0 行第 1 列 [85, 90]：学生 1 的数学成绩，一班 85，二班 90
# 第 1 行第 0 列 [78, 92]：学生 2 的语文成绩，一班 78，二班 92
# 以此类推
print('3. 沿 axis=-1（axis=2）堆叠（第二常用）')
stack2 = np.stack((class1, class2), axis=-1)
print("形状：", stack2.shape)  # (3, 4, 2)
print("\n结果：")
print(stack2)

1. 沿 axis=0 堆叠（最常用）
形状： (2, 3, 4)

结果：
[[[90 85 92 88]
  [78 95 80 91]
  [85 82 88 90]]

 [[88 90 85 92]
  [92 87 90 85]
  [80 93 87 89]]]
2. 沿 axis=1 堆叠（极少用
形状： (3, 2, 4)

结果：
[[[90 85 92 88]
  [88 90 85 92]]

 [[78 95 80 91]
  [92 87 90 85]]

 [[85 82 88 90]
  [80 93 87 89]]]
3. 沿 axis=-1（axis=2）堆叠（第二常用）
形状： (3, 4, 2)

结果：
[[[90 88]
  [85 90]
  [92 85]
  [88 92]]

 [[78 92]
  [95 87]
  [80 90]
  [91 85]]

 [[85 80]
  [82 93]
  [88 87]
  [90 89]]]
