# 1.列表如何转nd array

In [2]:
import numpy as np
list1=[1,2,3,4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [3]:
oneArray=np.array(list1) #列表转一维向量，格式上看，列表带逗号，向量不带逗号
print(oneArray)
print(type(oneArray))

[1 2 3 4]
<class 'numpy.ndarray'>


# 2.创建向量与矩阵

In [4]:
#创建一维数组（向量）
vec1=np.arange(1,11,2) #等价于先生成range(1,11,2)的列表，再转化为张量。 np.arange()返回的是ndarray
print(vec1)
print(type(vec1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [5]:
#二维列表转nd array
list2=[[1,2],[3,4],[5,6]] #每一个元素可以看成一个行向量

twoArray=np.array(list2)
print(twoArray) #一行一个列表，有形状的 。 也不带逗号
print(type(twoArray))
print(list2)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1, 2], [3, 4], [5, 6]]


In [6]:
# 二维数组转换为二维列表
twoArray.tolist() #ndarray转化为列表

[[1, 2], [3, 4], [5, 6]]

# 3.常用属性

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.ndim)    # 2 → 维度（几维数组）
print(arr.shape)   # (2, 3) → 形状（行数, 列数）  （0 axis，1axis）
print(arr.size)    # 6 → 元素总数
print(arr.dtype)   # int32 → 元素的数据类型   数据范围：-21亿~+21亿

# 👉 shape 是 ML 中最重要的属性，所有模型输入都要求固定的 shape（比如图像输入 shape=(224,224,3)） 

2
(2, 3)
6
int32


# 4.改变形状

In [8]:
M1=np.array([[1,2,3],[4,5,6]])
print(M1)

#方法一
M1.shape=(3,2) #改变形状后，地址没变
print(M1)

#方法二：
M2=M1.reshape(1,6)
print(M2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [9]:
# 转成三维
# 看括号，最外层是0轴，依次是1轴，2轴。 前面的要有整体思维，看后面的要看局部
vec2=np.arange(0,24,1)
T1=vec2.reshape(2,3,4) #看一个nd array，先看其形状，再依次看轴的元素。
print(T1)
print(T1.shape)
print(T1.ndim)

#以三维为例，轴0个数：矩阵个数，把矩阵当成一个整体    轴1：向量个数，以向量为单位   轴2：向量的每个分量    由此可以快速得出张量的尺寸shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


# 5.NumPy的数据类型

In [12]:
import random
f=np.array([1,2,3,4,5],dtype=np.int16) #给每个元素设置数据类型，可节省空间
print(f)
print(f.itemsize) #2B=16b

[1 2 3 4 5]
2


# 6.数组的计算

In [13]:
#1.算数运算，向量化
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)  # [ 6  8 10 12]
print(a - b)  # [-4 -4 -4 -4]
print(a * b)  # [ 5 12 21 32]
print(a / b)  # [0.2        0.33333333 0.42857143 0.5       ]
print(a ** 2) # [ 1  4  9 16]

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [14]:
# 2.广播机制：当两个数组形状不同时，NumPy 会自动扩展较小的数组（扩展copy一份自己），让它们形状匹配，从而进行运算。
#（一）向量+标量
a = np.array([[1,2,3], [4,5,6]])
print(a + 10)  # 每个元素都加10
# [[11 12 13]
#  [14 15 16]]

#（二）二维数组+一维数组（矩阵+向量)    
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10,20,30])  # shape=(3,) ，只有一行。       a,b的维度不匹配时，但有一个的维度（二者不相等的维）是1，即可广播。  例如：(10,128,128)第一个维度代表样本数，可以对单样本操作，再广播。

print(a + b)
# [[11 22 33]
#  [14 25 36]]

[[11 12 13]
 [14 15 16]]
[[11 22 33]
 [14 25 36]]


In [15]:
# 3.矩阵运算
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

# 矩阵乘法（两种写法等价）
print(np.dot(a, b))
print(a @ b)
# [[19 22]
#  [43 50]]

# 矩阵转置
print(a.T)
# [[1 3]
#  [2 4]]

# 矩阵求逆
print(np.linalg.inv(a))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
